server:
  port: 8082

spring:
  application:
    name: account
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb
      database: bankdb

# Customer Service URL for WebClient
customer:
  service:
    url: http://localhost:8081

logging:
  level:
    root: INFO
    com.bank: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
