server:
  port: 8082

spring:
  application:
    name: account
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bankdb
      database: bankdb

eureka:
  client:
    service-url:
      defaultZone: http://cbank-eurekaserver:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    hostname: ${HOSTNAME:account}

# Customer Service URL - Usar nombre del servicio en Eureka
customer:
  service:
    url: http://customer  # Solo el nombre, Eureka resuelve la ubicación

logging:
  level:
    root: INFO
    com.bank: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.cloud.config: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Configuración de Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        # Número de llamadas para calcular tasa de fallos
        sliding-window-size: 5
        # Tipo de ventana: COUNT_BASED o TIME_BASED
        sliding-window-type: COUNT_BASED
        # Umbral de fallos para abrir el circuito (50%)
        failure-rate-threshold: 50
        # Tiempo en estado OPEN antes de pasar a HALF_OPEN (en segundos)
        wait-duration-in-open-state: 10s
        # Número de llamadas permitidas en HALF_OPEN
        permitted-number-of-calls-in-half-open-state: 2
        # Llamadas mínimas antes de calcular tasa de fallos
        minimum-number-of-calls: 3
        # Transición automática de OPEN a HALF_OPEN
        automatic-transition-from-open-to-half-open-enabled: true
        # Excepciones que se consideran fallos
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
    instances:
      customerService:
        base-config: default      

  # Configuración de Retry (opcional pero complementario)
  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.InternalServerError
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
    instances:
      customerService:
        base-config: default

  # Configuración de Time Limiter (timeout)
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      customerService:
        base-config: default