server:
  port: 8083

spring:
  application:
    name: credit
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bankdb
      database: bankdb

eureka:
  client:
    service-url:
      defaultZone: http://cbank-eurekaserver:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    hostname: ${HOSTNAME:credit}

# Customer Service URL - Usar Eureka
customer:
  service:
    url: http://customer

logging:
  level:
    root: INFO
    com.bank: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.cloud.config: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Configuración de Resilience4j Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignore-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.NotFound
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - com.bank.credit.exception.CustomerNotFoundException
    instances:
      customerService:
        base-config: default      

  # Configuración de Retry (opcional pero complementario)
  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.InternalServerError
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
    instances:
      customerService:
        base-config: default

  # Configuración de Time Limiter (timeout)
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      customerService:
        base-config: default

kafka:
  consumer:
    group-id: credit-service-group