server:
  port: 8081

spring:
  application:
    name: customer
  data:
    mongodb:
      uri: mongodb://mongodb:27017/bankdb
      database: bankdb

eureka:
  client:
    service-url:
      defaultZone: http://cbank-eurekaserver:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    hostname: ${HOSTNAME:customer}

logging:
  level:
    root: INFO
    com.bank: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.cloud.config: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

kafka:
  consumer:
    group-id: customer-service-group