server:
  port: 8084

spring:
  application:
    name: transaction
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb
      database: bankdb

# Microservices URLs
account:
  service:
    url: http://localhost:8082

credit:
  service:
    url: http://localhost:8083

logging:
  level:
    root: INFO
    com.bank: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
